# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# Default manifest for installing postgresql instance(s) standalone
# AWS_PROFILE=datanexus ansible-playbook -e "project=demo application=postgresql domain=development  host_inventory=tag_Application_{{ application }} ansible_user=centos cloud=aws" site.yml
---
- hosts: "{{ host_inventory }}"
  vars_files:
    - vars/postgresql.yml
  roles: 
    - { role: install-packages, package_list: ['epel-release-7-9', 'https://download.postgresql.org/pub/repos/yum/{{ postgresql_major_version }}.{{ postgresql_minor_version }}/redhat/rhel-7-x86_64/pgdg-centos{{ postgresql_major_version }}{{ postgresql_minor_version }}-{{ postgresql_major_version }}.{{ postgresql_minor_version }}-3.noarch.rpm'] }
    - { role: install-packages, package_list: "{{ postgresql_package_list }}" }
    - { role: get-iface-addr, iface_name: "{{ postgresql_interface }}" }
    - { role: dn-postgresql, postgresql_addr: "{{ iface_addr }}" }

- hosts: "{{ host_inventory }}:&tag_Role_master"
  vars_files:
    - vars/postgresql.yml
  roles:
    - { role: master-streaming }

- hosts: "{{ host_inventory }}:&tag_Role_replica"
  vars_files:
    - vars/postgresql.yml
  roles:
    - { role: replica-streaming }
    
