# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# Default manifest for installing postgresql instance(s) standalone
# AWS_PROFILE=datanexus ansible-playbook -e "project=demo application=postgresql domain=development  host_inventory=tag_Application_{{ application }} ansible_user=centos" site.yml
---
- hosts: "{{ host_inventory }}"
  vars_files:
    - vars/postgresql.yml
  roles:
    - { role: install-packages, package_list: "{{ postgresql_package_list }}" }
    - { role: get-iface-addr, iface_name: "{{ postgresql_interface }}" }
    - { role: dn-postgresql, postgresql_addr: "{{ iface_addr }}" }