# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 
---
- name: Define postgresql_version.
  set_fact:
    postgresql_addr: "{{ postgresql_addr }}"
  when: postgresql_interface is not defined

- name: Define postgresql_version.
  set_fact:
    postgresql_version: "{{ postgresql_version }}"
  when: postgresql_version is not defined

- name: Define postgresql_data_dir.
  set_fact:
    postgresql_data_dir: "{{ postgresql_data_dir }}"
  when: postgresql_data_dir is not defined

- name: Define postgresql_bin_path.
  set_fact:
    postgresql_bin_path: "{{ postgresql_bin_path }}"
  when: postgresql_bin_path is not defined

- name: Define postgresql_config_path.
  set_fact:
    postgresql_config_path: "{{ postgresql_config_path }}"
  when: postgresql_config_path is not defined

- name: Define postgresql_daemon.
  set_fact:
    postgresql_daemon: "{{ postgresql_daemon }}"
  when: postgresql_daemon is not defined